# 分辨率展示工具
# Resolution Display Tool
# 程序由豆包AI生成，经人工修改完善
# The program is generated by DouBao AI, and is modified and improved manually
# 功能：展示不同分辨率在当前屏幕上的显示效果及相关信息
# Function: Display the display effect and related information of different resolutions on the current screen

import pygame
import sys
import ctypes
from fractions import Fraction

# 初始化 pygame
pygame.init()

# 处理高 DPI 缩放问题
user32 = ctypes.windll.user32
user32.SetProcessDPIAware()             # 告诉系统此程序支持高 DPI
dpi_value = user32.GetDpiForSystem()    # 获取系统 DPI 值
SCALE_FACTOR = dpi_value / 96           # 计算缩放比例 (96 是 100% 缩放的 DPI)

# 获取实际屏幕分辨率
FULLSCREEN_WIDTH = int(user32.GetSystemMetrics(0))
FULLSCREEN_HEIGHT = int(user32.GetSystemMetrics(1))

# 输出调试信息到控制台
print()
print(f"dpi_value: {dpi_value}")
print(f"SCALE_FACTOR: {SCALE_FACTOR}")
print(f"FULLSCREEN_WIDTH: {FULLSCREEN_WIDTH}")
print(f"FULLSCREEN_HEIGHT: {FULLSCREEN_HEIGHT}")

# 要展示的分辨率列表
resolutions = [
    (640, 480),
    (800, 600),
    (1024, 768),
    (1152, 864),
    (1280, 720),
    (1280, 1024),
    (1366, 768),
    (1440, 900),
    (1440, 1050),
    (1440, 1080),
    (1600, 900),
    (1600, 1024),
    (1600, 1200),
    (1920, 1080),
    (1920, 1200),
    (1920, 1440),
    (2048, 1152),
    (2560, 1440)
]

# 创建全屏窗口
# screen = pygame.display.set_mode((FULLSCREEN_WIDTH, FULLSCREEN_HEIGHT), pygame.FULLSCREEN)
screen = pygame.display.set_mode((FULLSCREEN_WIDTH, FULLSCREEN_HEIGHT), pygame.NOFRAME)
pygame.display.set_caption("分辨率展示工具")

# 设置字体
pygame.font.init()
font_size = int(24 * SCALE_FACTOR)          # 字体大小随缩放比例调整
small_font_size = int(18 * SCALE_FACTOR)    # 字体大小随缩放比例调整
font = pygame.font.SysFont("SimHei", font_size)
small_font = pygame.font.SysFont("SimHei", small_font_size)

# 初始状态
try:
    current_index = resolutions.index((1920, 1080))     # 当前显示的分辨率索引默认展示 1920×1080 分辨率
except ValueError:
    current_index = 0   # 如果列表中没有 1920×1080，则默认第一个
    print("(1920, 1080) is not in list")
center_mode = False     # 显示模式，True 为居中，False 为左上角

# 帧率控制
clock = pygame.time.Clock()
FPS = 60    # 限制帧率为 60

# 计算分辨率的长宽比
def get_aspect_ratio(width, height):
    ratio = Fraction(width, height).limit_denominator()
    return f"{ratio.numerator}:{ratio.denominator}"

# 计算缩放比例信息 - 分别计算宽和高的比例
def get_scale_info(width, height):
    scale_w = (width / FULLSCREEN_WIDTH) * 100
    scale_h = (height / FULLSCREEN_HEIGHT) * 100
    zoom_w = (FULLSCREEN_WIDTH / width) * 100
    zoom_h = (FULLSCREEN_HEIGHT / height) * 100
    return (f"{scale_w:.1f}%", f"{scale_h:.1f}%", f"{zoom_w:.1f}%", f"{zoom_h:.1f}%")

# 主循环
running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE:
                running = False
            elif event.key == pygame.K_DOWN:
                current_index = (current_index + 1) % len(resolutions)
            elif event.key == pygame.K_UP:
                current_index = (current_index - 1) % len(resolutions)
            elif event.key == pygame.K_SPACE:
                center_mode = not center_mode
    
    # 填充背景为深灰色
    screen.fill((30, 30, 30))
    
    # 当前分辨率信息
    current_width, current_height = resolutions[current_index]
    aspect_ratio = get_aspect_ratio(current_width, current_height)
    scale_w, scale_h, zoom_w, zoom_h = get_scale_info(current_width, current_height)
    
    # 计算显示位置
    if center_mode:
        x = (FULLSCREEN_WIDTH - current_width) // 2
        y = (FULLSCREEN_HEIGHT - current_height) // 2
        mode_text = "当前模式：居中显示"
    else:
        x = 0   # 左上角显示
        y = 0
        mode_text = "当前模式：左上角显示"
    
    # 绘制分辨率区域白色边框浅灰色填充
    pygame.draw.rect(screen, (255, 255, 255), (x, y, current_width, current_height), 2)
    inner_rect = pygame.Rect(x + 1, y + 1, current_width - 2, current_height - 2)
    screen.fill((100, 100, 100), inner_rect)
    
    # 显示当前分辨率信息
    info_text = font.render(
        f"{current_width}×{current_height}  比例 {aspect_ratio}  "
        f"宽占比 {scale_w}  高占比 {scale_h}  "
        f"放大倍数  宽 {zoom_w}  高 {zoom_h}", 
        True, (255, 255, 0)
    )
    info_y = int(50 * SCALE_FACTOR)
    info_rect = info_text.get_rect(center=(FULLSCREEN_WIDTH // 2, info_y))
    screen.blit(info_text, info_rect)
    
    # 显示模式信息
    mode_display = font.render(mode_text, True, (0, 255, 255))
    mode_y = int(90 * SCALE_FACTOR)
    mode_rect = mode_display.get_rect(center=(FULLSCREEN_WIDTH // 2, mode_y))
    screen.blit(mode_display, mode_rect)
    
    # 绘制分辨率列表框
    list_box_width = int(300 * SCALE_FACTOR)    # 减小列表框宽度
    item_height = int(25 * SCALE_FACTOR)        # 减小每个列表项高度，减少间隔
    list_box_height = int(10 * SCALE_FACTOR + 40 * SCALE_FACTOR + len(resolutions) * item_height)   # 自适应高度
    list_box_x = int(20 * SCALE_FACTOR)
    list_box_y = int(150 * SCALE_FACTOR)
    
    # 列表框背景
    pygame.draw.rect(screen, (50, 50, 50), 
                    (list_box_x, list_box_y, list_box_width, list_box_height))
    pygame.draw.rect(screen, (200, 200, 200), 
                    (list_box_x, list_box_y, list_box_width, list_box_height), 2)
    
    # 列表标题
    list_title = font.render("分辨率列表", True, (255, 255, 255))
    screen.blit(list_title, (list_box_x + int(10 * SCALE_FACTOR), list_box_y + int(10 * SCALE_FACTOR)))
    
    # 绘制所有分辨率
    start_y = list_box_y + int(40 * SCALE_FACTOR)   # 标题下方开始
    
    for i, (w, h) in enumerate(resolutions):
        item_y = start_y + i * item_height
        
        # 高亮当前选中的分辨率
        if i == current_index:
            pygame.draw.rect(screen, (70, 70, 150), 
                           (list_box_x + 2, item_y - 2 * SCALE_FACTOR, list_box_width - 4, item_height - 2 * SCALE_FACTOR))
        
        # 显示分辨率
        ratio = get_aspect_ratio(w, h)
        if i == current_index:
            item_text = small_font.render(f"{w}×{h}  ({ratio})", True, (255, 255, 0))
        else:
            item_text = small_font.render(f"{w}×{h}  ({ratio})", True, (200, 200, 200))
        
        screen.blit(item_text, (list_box_x + int(20 * SCALE_FACTOR), item_y))
    
    # 操作提示
    hint = font.render(
        "按上下方向键切换分辨率 | 空格键切换显示模式 | ESC键退出", 
        True, (200, 200, 200)
    )
    hint_y = FULLSCREEN_HEIGHT - int(50 * SCALE_FACTOR)
    hint_rect = hint.get_rect(center=(FULLSCREEN_WIDTH // 2, hint_y))
    screen.blit(hint, hint_rect)
    
    # 控制帧率
    clock.tick(FPS)

    # 更新显示
    pygame.display.flip()

print()
pygame.quit()
sys.exit()
